version: '3'
services:
  database:
    restart: always
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    volumes:
      - ./src/main/resources/db/migration/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./src/main/resources/db/migration/data.sql:/docker-entrypoint-initdb.d/2.sql

