CREATE TABLE IF NOT EXISTS services (
  id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(10)
);
